- name: Variable on play level
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}



- name: variables from file on play level
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{UR}}


#- name: Variable Precedence
# hosts: all
    #  vars:
    #URL: play.example.com
    #vars_files:
    #- sample-vars.yml
    tasks:
    -name: Print URL
      ansible.builtin.debug:
      msg: URL == {{URL}}
      vars:
      URL: task.example.com


- name: Register a variable
  hosts: all
  tasks:
    - name: Run uptime command
      ansible.builtin.shell: uptime
      register: OUT
    - name: Print out variable
      ansible.builtin.debug:
        msg: "{{OUT.stdout}}"