- name: Install Maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: Setup App User and App Code
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: Stop {{COMPONENT}} service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: stopped
  ignore_errors: yes

- name: Configure SystemD for {{COMPONENT}}
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd