- name: Setup Repo file for NodeJS
  ansible.builtin.copy:
    src: nodejs.repo
    dest: /etc/yum.repos.d/nodejs.repo

- name: Install NodeJS
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Setup App User and App Code
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: Configure SystemD for {{COMPONENT}}
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd