route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: "email"
    email_configs:
      - to: "pathipati.reshma@gmail.com"
        from: "pathipati.reshma@gmail.com"
        smarthost: "email-smtp.us-east-1.amazonaws.com:587"
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']