# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

rule_files:
  - alerts.yml


# A scrape configuration containing exactly one endpoint to scrape:

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ec2-nodes-sd"
    {% raw %}
#    relabel_configs:
#      - source_labels: ["__meta_ec2_tag_Name"]
#        target_label: "nodeName"
#      - source_labels: ["__meta_ec2_tag_ENV"]
#        target_label: "env"
    {% endraw %}
    ec2_sd_configs:
      - region: us-east-1 ## N. Virginia
  {% raw %}
#        access_key: {{AWS_ACCESS_KEY}}
#        secret_key: {{AWS_SECRET_KEY}}
  {% endraw %}
          port: 9100
          filters:
            - name: "tag:Monitor"
              values: ["yes"]